steps:
  # Build a 'good' image
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
      - -c
      - |
        docker build -t gcr.io/$PROJECT_ID/nodejsexpressapi:latest .
    id: build
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
    - -c
    - |
      docker push gcr.io/$PROJECT_ID/nodejsexpressapi:latest &&
      docker image inspect gcr.io/$PROJECT_ID/nodejsexpressapi:latest --format '{{index .RepoDigests 0}}' > image-digest.txt &&
      cat image-digest.txt
    id: push
  - name: gcr.io/$PROJECT_ID/kritis-signer
    entrypoint: /bin/bash
    args:
    - -c
    - |
      /kritis/signer \
      -v=10 \
      -alsologtostderr \
      -image=$(/bin/cat image-digest.txt) \
      -policy=policy.yaml \
      -kms_key_name=${_KMS_KEY_NAME} \
      -kms_digest_alg=${_KMS_DIGEST_ALG} \
      -note_name=${_NOTE_NAME}
    waitFor: push
    id: vulnsign
substitutions:
    _KMS_KEY_NAME: MISSING_KMS_KEY_NAME # Use `gcloud builds submit --substitutions ` to set this value
    _KMS_DIGEST_ALG: MISSING_KMS_DIGEST_ALG  # Use `gcloud builds submit --substitutions ` to set this value
    _NOTE_NAME: MISSING_NOTE_NAME  # Use `gcloud builds submit --substitutions ` to set this value
images: ['gcr.io/$PROJECT_ID/nodejsexpressapi:latest']